platform :ios, '6.1'

# needed
pod 'AFNetworking'
pod 'SMWheelControl'

# might be useful (but currently unused)
#pod 'Reachability'
#pod 'SDWebImage'
#pod 'AsyncImageView'

# depends on old 'AFNetworking', '1.x'
#pod 'RestKit', '0.22.0'

# useful (but its a paid app and needs to be removed for store)
#pod 'Reveal-iOS-SDK'
